---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.6.0
  data_bags_path: '../../data_bags'
  environments_path: '../../environments'
  nodes_path: '../../nodes'
  roles_path: '../../roles'
  client_rb:
    environment: development

platforms:
  - name: centos-6.5
    driver_config:
      box: centos_6.5_packer
      box_url: https://s3.amazonaws.com/o2o-public/centos_6.5_packer_provisionerless.box
  - name: centos-7.1
    driver_config:
      box: centos_7.1
      box_url: https://github.com/holms/vagrant-centos7-box/releases/download/7.1.1503.001/CentOS-7.1.1503-x86_64-netboot.box

suites:
  - name: default
    driver:
      vm_hostname: false
      customize:
        memory: 2048
      network:
      - ["private_network", {ip: "33.33.33.221"}]
    run_list:
      - recipe[genie-cookbook::default]